version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "main"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "node-fetch"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "chai"
        update-types:
          - "version-update:semver-major"
    open-pull-requests-limit: 10
