name: CI

on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Check npm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-18.x-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Upload out files
        uses: actions/upload-artifact@v3
        with:
          name: build-out-files
          path: |
            index.js
            index.d.ts

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        node-version:
          - '12.x'
          - '14.x'
          - '16.x'
          - '18.x'
          - '20.x'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Check npm cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm i

      - name: Download built files
        uses: actions/download-artifact@v3
        with:
          name: build-out-files

      - name: Test
        run: npm test
  
  coverage:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Check npm cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-16.x-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  success-all-test:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
    steps:
      - uses: technote-space/workflow-conclusion-action@v3

      - name: Check failure
        if: env.WORKFLOW_CONCLUSION != 'success'
        run: exit 1
        
      - name: Success
        run: echo "All done"
        if: ${{ success() }}
